# Generated by Django 3.1.2 on 2020-10-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fifty', models.IntegerField(max_length=100)),
                ('twentyfive', models.IntegerField(max_length=100)),
                ('twelve', models.IntegerField(max_length=100)),
                ('oxygen', models.IntegerField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GasL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fifty', models.IntegerField(max_length=100)),
                ('twentyfive', models.IntegerField(max_length=100)),
                ('twelve', models.IntegerField(max_length=100)),
                ('oxygen', models.IntegerField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
