# Generated by Django 3.1.2 on 2020-11-11 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201022_0920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GasE',
        ),
        migrations.DeleteModel(
            name='GasL',
        ),
    ]
