# Generated by Django 4.2 on 2023-04-12 16:22

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
