# Generated by Django 4.2 on 2023-04-12 16:47

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_blogpost_content_alter_blogpost_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
