# Generated by Django 3.2.6 on 2021-11-08 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Bro', 'Bro'), ('Sis', 'Sis')], max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='watchman_pics/index.jpg', null=True, upload_to='watchman_pics')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('whatsapp_number', models.CharField(max_length=12)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('residence', models.CharField(blank=True, max_length=150, null=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('is_worker', models.CharField(choices=[('Worker', 'Worker'), ('Non-worker', 'Non-Worker')], max_length=20)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('other', 'Other')], max_length=20)),
                ('home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('home_church', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=50, null=True)),
                ('next_of_kin_number', models.CharField(blank=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
