# Generated by Django 3.2.6 on 2021-10-31 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('bro', 'Bro'), ('sis', 'Sis')], max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('whatsapp_number', models.CharField(max_length=12)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('residence', models.CharField(blank=True, max_length=150, null=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('is_worker', models.CharField(choices=[('worker', 'Worker'), ('non-worker', 'Non-Worker')], max_length=20)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(choices=[('first_year', '100'), ('second_year', '200'), ('third_year', '300'), ('fouth_year', '400'), ('final_year', '500'), ('other', 'Other')], max_length=20)),
                ('home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('home_church', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=50, null=True)),
                ('next_of_kin_number', models.CharField(blank=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
