# Generated by Django 3.2.6 on 2021-11-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='watchman_pics'),
        ),
    ]
